datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 'postgres'
    schema-generate: NONE
    dialect: POSTGRES

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate

kafka:
  bootstrap:
    servers: "${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}"

micronaut:
  application:
    name: product-catalog
  metrics:
    enabled: true
  security:
    authentication: bearer
    token:
      jwt:
        enabled: true
        signatures:
          generator:
            secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'

endpoints:
  health:
    enabled: true
    sensitive: false
  metrics:
    enabled: true
    sensitive: false

consul:
  client:
    default-zone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
    registration:
      enabled: true

flyway:
  datasources:
    default:
      enable: true
