version: '3'

services:
  postgres:
    image: "postgres:latest"
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  consul:
    image: "consul:latest"
    container_name: consul
    hostname: consul
    ports:
      - "8500:8500"
  kafkaserver:
    image: "spotify/kafka:latest"
    container_name: kafka
    hostname: kafkaserver
    ports:
      - "2181:2181"
      - "9092:9092"
#    environment:
#      ADVERTISED_HOST: kafkaserver
#      ADVERTISED_PORT: 9092
