version: '3'

services:
  postgres:
    image: "postgres:latest"
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  consul:
    image: "consul:latest"
    container_name: consul
    hostname: consul
    ports:
      - "8500:8500"
  kafkaserver:
    image: "wurstmeister/kafka:latest" # TODO: https://hub.docker.com/r/wurstmeister/kafka/
    container_name: kafka
    hostname: kafkaserver
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  zookeeper:
    image: "wurstmeister/zookeeper:latest"
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
