CREATE TABLE PRODUCT
(
    id       BIGSERIAL PRIMARY KEY,
    name     TEXT NOT NULL UNIQUE,
    ean_code VARCHAR(13)
);

CREATE TABLE PRODUCT_UNIT
(
    id   BIGSERIAL PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE PRODUCT_CATEGORY
(
    id   BIGSERIAL PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);
