CREATE TABLE PRODUCT
(
    ID                    BIGSERIAL PRIMARY KEY,
    NAME                  TEXT NOT NULL UNIQUE,
    EAN_CODE              VARCHAR(13),
    AGGREGATE_STATUS      TEXT NOT NULL,
    VERSION               BIGINT NOT NULL,
    LAST_CHANGE_DATE      TIMESTAMP,
    LAST_CHANGE_AUTHOR_ID BIGINT
);

CREATE TABLE PRODUCT_UNIT
(
    ID                    BIGSERIAL PRIMARY KEY,
    NAME                  TEXT NOT NULL UNIQUE,
    AGGREGATE_STATUS      TEXT NOT NULL,
    VERSION               BIGINT NOT NULL,
    LAST_CHANGE_DATE      TIMESTAMP,
    LAST_CHANGE_AUTHOR_ID BIGINT
);

CREATE TABLE PRODUCT_CATEGORY
(
    ID                    BIGSERIAL PRIMARY KEY,
    NAME                  TEXT NOT NULL UNIQUE,
    AGGREGATE_STATUS      TEXT NOT NULL,
    VERSION               BIGINT NOT NULL,
    LAST_CHANGE_DATE      TIMESTAMP,
    LAST_CHANGE_AUTHOR_ID BIGINT
);
