CREATE TABLE RECIPE
(
    ID                    BIGSERIAL PRIMARY KEY,
    NAME                  TEXT NOT NULL UNIQUE,
    INSTRUCTIONS_BODY     TEXT NOT NULL,
    AGGREGATE_STATUS      TEXT NOT NULL,
    VERSION               BIGINT NOT NULL,
    LAST_CHANGE_DATE      TIMESTAMP,
    LAST_CHANGE_AUTHOR_ID BIGINT
);
