name: GraalVM CE CI
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.m2/repository
          key: ${{ runner.os }}-gradle-test-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-test-
      - name: Setup GraalVM CE
        uses: DeLaGuardo/setup-graalvm@4.0
        with:
          graalvm: 21.2.0
          java: java11
          arch: amd64
      - name: Install Native Image
        run: gu install native-image
      - name: DockerHub login # TODO: support other registries?
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # TODO Can we split this per each service?
      # JOB FAILS (even locally) with java.lang.RuntimeException: java.io.IOException: native write() failed : Connection reset by peer
      - name: Build And Push Docker Image (Product Catalog)
        working-directory: product-catalog
        env:
          DOCKER_REPOSITORY_PATH: ${{ secrets.DOCKER_REPOSITORY_PATH }}
          TESTCONTAINERS_RYUK_DISABLED: true
        run: |
          export DOCKER_IMAGE=`echo "${DOCKER_REPOSITORY_PATH}/product-catalog" | sed -e 's#//#/#' -e 's#^/##'`
          ./gradlew check dockerPushNative --no-daemon
